version: '3.1'

services:
  book-api:
    image: book-api
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./ansible/templates/appsettings.Production.json:/app/appsettings.Production.json
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://0.0.0.0:3000"
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "web"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "BookDB"
